apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backend
  description: This is the api to expose.
  tags:
    - java
    - quarkus
  annotations:
    github.com/project-slug: POC-CONSENSUS/backend
    quay.io/repository-slug: rh_ee_symartin/poc
    backstage.io/kubernetes-id: backend
spec:
  type: service
  lifecycle: experimental
  owner: group:poc-consensus/awesometeam
  system: naming-convention-generator
  providesApis:
    - assets-api
